version: "3.9"

services:
  jellyfin:
    container_name: jellyfin
    image: linuxserver/jellyfin
    restart: unless-stopped
    environment:
      PUID: 0
      PGID: 0
      TZ: Asia/Manila
    volumes:
      - ./jellyfin:/config
      - /mnt/e/media:/data
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
      - 1900:1900/udp
