services:
  caddy:
    container_name: caddy
    image: caddy:2.8.4-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    cap_add:
      - NET_ADMIN
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/pki_local:/data/caddy/pki/authorities/local
    environment:
      DOMAIN: ${DOMAIN}
      FRIGATE_HOST: ${FRIGATE_HOST}
      JELLYFIN_HOST: ${JELLYFIN_HOST}
      SERVARR_HOST: ${SERVARR_HOST}
    networks:
      - internal

  homepage:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:latest
    restart: unless-stopped
    volumes:
      - ./homepage:/app/config
    environment:
      PUID: $PUID
      PGID: $PGID
    networks:
      - internal

networks:
  internal:
    name: internal
    driver: bridge
