#
# Use this configuration with WireGuard client
#
[Interface]
Address = 10.10.10.10/16
PrivateKey = XXXX
DNS = 6.9.6.9, 9.6.9.6
[Peer]
PublicKey = XXXX
AllowedIPs = 0.0.0.0/0
Endpoint = 9.9.9.9:51820
