version: "3.9"

services:
  caddy:
    container_name: caddy
    image: caddy
    restart: unless-stopped
    volumes:
      - ./caddy/Caddyfile:/opt/Caddyfile
      - ./caddy/pki_local:/data/caddy/pki/authorities/local
