version: "3.9"

services:
  caddy:
    container_name: caddy
    image: caddy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy/Caddyfile:/opt/Caddyfile
      - ./caddy/pki_local:/data/caddy/pki/authorities/local
    environment:
      DOMAIN: ${DOMAIN}
    networks:
      internal:
      tailscale:
        ipv4_address: "172.25.0.4"

  tailscale:
    profiles: ["tailscale"]
    container_name: tailscale
    image: tailscale/tailscale:stable
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - tailscale_lib:/var/lib/tailscale
    environment:
      TS_HOSTNAME: doge-server
      TS_AUTHKEY: ${TAILSCALE_AUTH_KEY}
      TS_STATE_DIR: /var/lib/tailscale
      TS_ROUTES: "172.25.0.0/16"
    networks:
      tailscale:
        ipv4_address: "172.25.0.2"

  tailscale_dns:
    profiles: ["tailscale"]
    image: dockurr/dnsmasq
    container_name: dnsmasq
    restart: unless-stopped
    volumes:
      - ./tailscale/dnsmasq.conf:/etc/dnsmasq.conf
    networks:
      tailscale:
        ipv4_address: "172.25.0.3"

volumes:
  tailscale_lib:

networks:
  internal:
    name: internal
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.22.0.0/16"
  tailscale:
    name: tailscale
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.25.0.0/16"
