arch: amd64
cores: 2
features: keyctl=1,fuse=1,nesting=1
hostname: main
memory: 2048
net0: name=eth0,bridge=vmbr0,gw=10.20.1.1,hwaddr=AA:AA:AA:AA:AA:AA,ip=10.20.1.44/24,type=veth
onboot: 1
ostype: alpine
rootfs: lvm:vm-102-disk-0,size=4G
swap: 512
tags: proxmox-helper-scripts
unprivileged: 1
