services:
  caddy:
    container_name: caddy
    image: caddy:2.8.4-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    cap_add:
      - NET_ADMIN
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/pki_local:/data/caddy/pki/authorities/local
      - ./caddy/assets:/srv/assets
    environment:
      DOMAIN: ${DOMAIN}
      OPENWRT_ROUTER_HOST: ${OPENWRT_ROUTER_HOST}
      OPENWRT_AP0_HOST: ${OPENWRT_AP0_HOST}
      OPENWRT_AP1_HOST: ${OPENWRT_AP1_HOST}
      OPENWRT_AP2_HOST: ${OPENWRT_AP2_HOST}
      OPENWRT_AP3_HOST: ${OPENWRT_AP3_HOST}
      PIHOLE_HOST: ${PIHOLE_HOST}
      HOME_ASSISTANT_HOST: ${HOME_ASSISTANT_HOST}
      FRIGATE_HOST: ${FRIGATE_HOST}
      Z2M_HOST: ${Z2M_HOST}
      NODE_RED_HOST: ${NODE_RED_HOST}
      JELLYFIN_HOST: ${JELLYFIN_HOST}
      QBITTORRENT_HOST: ${QBITTORRENT_HOST}
      PROWLARR_HOST: ${PROWLARR_HOST}
      RADARR_HOST: ${RADARR_HOST}
      SONARR_HOST: ${SONARR_HOST}
      BAZARR_HOST: ${BAZARR_HOST}
      VAULTWARDEN_HOST: ${VAULTWARDEN_HOST}
    networks:
      - internal

  homepage:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:latest
    restart: unless-stopped
    volumes:
      - ./homepage/config:/app/config
    environment:
      PUID: $PUID
      PGID: $PGID
      LOG_TARGETS: stdout
      HOMEPAGE_VAR_DOMAIN: ${DOMAIN}
      HOMEPAGE_VAR_GLANCES_HOST: ${GLANCES_HOST}
      HOMEPAGE_VAR_GLANCES_USERNAME: ${GLANCES_USERNAME}
      HOMEPAGE_VAR_GLANCES_PASSWORD: ${GLANCES_PASSWORD}
      HOMEPAGE_VAR_OPENWRT_ROUTER_HOST: ${OPENWRT_ROUTER_HOST}
      HOMEPAGE_VAR_OPENWRT_ROUTER_PASSWORD: ${OPENWRT_ROUTER_PASSWORD}
      HOMEPAGE_VAR_OPENWRT_AP0_HOST: ${OPENWRT_AP0_HOST}
      HOMEPAGE_VAR_OPENWRT_AP1_HOST: ${OPENWRT_AP1_HOST}
      HOMEPAGE_VAR_OPENWRT_AP2_HOST: ${OPENWRT_AP2_HOST}
      HOMEPAGE_VAR_OPENWRT_AP3_HOST: ${OPENWRT_AP3_HOST}
      HOMEPAGE_VAR_PIHOLE_HOST: ${PIHOLE_HOST}
      HOMEPAGE_VAR_PIHOLE_API_KEY: ${PIHOLE_API_KEY}
      HOMEPAGE_VAR_HOME_ASSISTANT_HOST: ${HOME_ASSISTANT_HOST}
      HOMEPAGE_VAR_FRIGATE_HOST: ${FRIGATE_HOST}
      HOMEPAGE_VAR_Z2M_HOST: ${Z2M_HOST}
      HOMEPAGE_VAR_NODE_RED_HOST: ${NODE_RED_HOST}
      HOMEPAGE_VAR_JELLYFIN_HOST: ${JELLYFIN_HOST}
      HOMEPAGE_VAR_JELLYFIN_API_KEY: ${JELLYFIN_API_KEY}
      HOMEPAGE_VAR_GLUETUN_HOST: ${GLUETUN_HOST}
      HOMEPAGE_VAR_QBITTORRENT_HOST: ${QBITTORRENT_HOST}
      HOMEPAGE_VAR_PROWLARR_HOST: ${PROWLARR_HOST}
      HOMEPAGE_VAR_PROWLARR_API_KEY: ${PROWLARR_API_KEY}
      HOMEPAGE_VAR_RADARR_HOST: ${RADARR_HOST}
      HOMEPAGE_VAR_RADARR_API_KEY: ${RADARR_API_KEY}
      HOMEPAGE_VAR_SONARR_HOST: ${SONARR_HOST}
      HOMEPAGE_VAR_SONARR_API_KEY: ${SONARR_API_KEY}
      HOMEPAGE_VAR_BAZARR_HOST: ${BAZARR_HOST}
      HOMEPAGE_VAR_BAZARR_API_KEY: ${BAZARR_API_KEY}
      HOMEPAGE_VAR_VAULTWARDEN_HOST: ${VAULTWARDEN_HOST}
      HOMEPAGE_VAR_DISK0_LABEL: ${DISK0_LABEL}
      HOMEPAGE_VAR_DISK1_LABEL: ${DISK1_LABEL}
      HOMEPAGE_VAR_DISK2_LABEL: ${DISK2_LABEL}
      HOMEPAGE_VAR_DISK3_LABEL: ${DISK3_LABEL}
      HOMEPAGE_VAR_DISK0_MOUNT_POINT: ${DISK0_MOUNT_POINT}
      HOMEPAGE_VAR_DISK1_MOUNT_POINT: ${DISK1_MOUNT_POINT}
      HOMEPAGE_VAR_DISK2_MOUNT_POINT: ${DISK2_MOUNT_POINT}
      HOMEPAGE_VAR_DISK0_NAME: ${DISK0_NAME}
      HOMEPAGE_VAR_DISK1_NAME: ${DISK1_NAME}
      HOMEPAGE_VAR_DISK2_NAME: ${DISK2_NAME}
      HOMEPAGE_VAR_DISK3_NAME: ${DISK3_NAME}
      HOMEPAGE_VAR_DISK0_SENSOR_NAME: ${DISK0_SENSOR_NAME}
      HOMEPAGE_VAR_DISK1_SENSOR_NAME: ${DISK1_SENSOR_NAME}
      HOMEPAGE_VAR_DISK2_SENSOR_NAME: ${DISK2_SENSOR_NAME}
      HOMEPAGE_VAR_DISK3_SENSOR_NAME: ${DISK3_SENSOR_NAME}
    networks:
      - internal

networks:
  internal:
    name: internal
    driver: bridge
