arch: amd64
cores: 1
features: keyctl=1,fuse=1,nesting=1
hostname: arr-stack
memory: 1024
net0: name=eth0,bridge=vmbr0,gw=10.20.1.1,hwaddr=AA:AA:AA:AA:AA:AA,ip=10.20.1.43/24,type=veth
mp0: /mnt/pve/storage0/media,mp=/mnt/media
onboot: 1
ostype: alpine
rootfs: lvm:vm-123-disk-0,size=2G
swap: 512
tags: proxmox-helper-scripts
unprivileged: 1
lxc.cgroup2.devices.allow: c 10:200 rwm
lxc.mount.entry: /dev/net dev/net none bind,create=dir
lxc.idmap: u 0 100000 65536
lxc.idmap: g 0 0 1
lxc.idmap: g 1 100000 65535
