# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json

# A starter config to use with Recyclarr. Most values are set to "reasonable defaults". Update the
# values below as needed for your instance. You will be required to update the API Key and URL for
# each instance you want to use.
#
# Many optional settings have been omitted to keep this template simple. Note that there's no "one
# size fits all" configuration. Please refer to the guide to understand how to build the appropriate
# configuration based on your hardware setup and capabilities.
#
# For any lines that mention uncommenting YAML, you simply need to remove the leading hash (`#`).
# The YAML comments will already be at the appropriate indentation.
#
# For more details on the configuration, see the Configuration Reference on the wiki here:
# https://recyclarr.dev/wiki/yaml/config-reference/

# Configuration specific to Sonarr
sonarr:
  series:
    media_naming:
      series: default
      season: default
      episodes:
        rename: true
        standard: default
        daily: default
        anime: default

    include:
      # == WEB-1080p
      - template: sonarr-quality-definition-series
      - template: sonarr-v4-quality-profile-web-1080p
      - template: sonarr-v4-custom-formats-web-1080p

      # == Anime (Sonarr)
      - template: sonarr-quality-definition-anime
      - template: sonarr-v4-quality-profile-anime
      - template: sonarr-v4-custom-formats-anime

    custom_formats:
      # == Anime (Sonarr)
      - trash_ids:
          - 026d5aadd1a6b4e550b134cb6c72b3ca # Uncensored
        quality_profiles:
          - name: Remux-1080p - Anime
            score: 0 # Adjust scoring as desired

      - trash_ids:
          - b2550eb333d27b75833e25b8c2557b38 # 10bit
        quality_profiles:
          - name: Remux-1080p - Anime
            score: 0 # Adjust scoring as desired

      - trash_ids:
          - 418f50b10f1907201b6cfdf881f467b7 # Anime Dual Audio
        quality_profiles:
          - name: Remux-1080p - Anime
            score: 0 # Adjust scoring as desired

# Configuration specific to Radarr.
radarr:
  movies:
    media_naming:
      folder: default
      movie:
        rename: true
        standard: default

    include:
      # == Remux + WEB 1080p
      - template: radarr-quality-definition-movie
      - template: radarr-quality-profile-remux-web-1080p
      - template: radarr-custom-formats-remux-web-1080p

      # == Anime (Radarr)
      - template: radarr-quality-definition-movie
      - template: radarr-quality-profile-anime
      - template: radarr-custom-formats-anime

    custom_formats:
      # == Remux + WEB 1080p
      # Audio
      - trash_ids:
          # Uncomment the next section to enable Advanced Audio Formats
          # - 496f355514737f7d83bf7aa4d24f8169 # TrueHD Atmos
          # - 2f22d89048b01681dde8afe203bf2e95 # DTS X
          # - 417804f7f2c4308c1f4c5d380d4c4475 # ATMOS (undefined)
          # - 1af239278386be2919e1bcee0bde047e # DD+ ATMOS
          # - 3cafb66171b47f226146a0770576870f # TrueHD
          # - dcf3ec6938fa32445f590a4da84256cd # DTS-HD MA
          # - a570d4a0e56a2874b64e5bfa55202a1b # FLAC
          # - e7c2fcae07cbada050a0af3357491d7b # PCM
          # - 8e109e50e0a0b83a5098b056e13bf6db # DTS-HD HRA
          # - 185f1dd7264c4562b9022d963ac37424 # DD+
          # - f9f847ac70a0af62ea4a08280b859636 # DTS-ES
          # - 1c1a4c5e823891c75bc50380a6866f73 # DTS
          # - 240770601cc226190c367ef59aba7463 # AAC
          # - c2998bd0d90ed5621d8df281e839436e # DD
        quality_profiles:
          - name: Remux + WEB 1080p

      # Movie Versions
      - trash_ids:
          - 9f6cbff8cfe4ebbc1bde14c7b7bec0de # IMAX Enhanced
        quality_profiles:
          - name: Remux + WEB 1080p
            # score: 0 # Uncomment this line to disable prioritised IMAX Enhanced releases

      # == Anime (Radarr)
      - trash_ids:
          - 064af5f084a0a24458cc8ecd3220f93f # Uncensored
        quality_profiles:
          - name: Remux-1080p - Anime
            score: 0 # Adjust scoring as desired

      - trash_ids:
          - a5d148168c4506b55cf53984107c396e # 10bit
        quality_profiles:
          - name: Remux-1080p - Anime
            score: 0 # Adjust scoring as desired

      - trash_ids:
          - 4a3b087eea2ce012fcc1ce319259a3be # Anime Dual Audio
        quality_profiles:
          - name: Remux-1080p - Anime
            score: 0 # Adjust scoring as desired
