arch: amd64
cores: 2
features: keyctl=1,fuse=1,nesting=1
hostname: jellyfin
memory: 2048
net0: name=eth0,bridge=vmbr0,gw=10.20.1.1,hwaddr=AA:AA:AA:AA:AA:AA,ip=10.20.1.42/24,type=veth
net1: name=eth1,bridge=vmbr0,hwaddr=BB:BB:BB:BB:BB:BB,ip=10.20.75.10/24,tag=75,type=veth
onboot: 1
ostype: debian
rootfs: lvm:vm-122-disk-2,size=4G
mp0: lvm:vm-122-disk-3,mp=/cache,size=8G
mp1: /mnt/pve/storage0/media,mp=/mnt/media
swap: 1024
tags: proxmox-helper-scripts
unprivileged: 1
lxc.cgroup2.devices.allow: c 195:0 rwm
lxc.cgroup2.devices.allow: c 195:255 rwm
lxc.cgroup2.devices.allow: c 234:0 rwm
lxc.cgroup2.devices.allow: c 234:1 rwm
lxc.cgroup2.devices.allow: c 237:1 rwm
lxc.cgroup2.devices.allow: c 237:2 rwm
lxc.mount.entry: /dev/nvidia0 dev/nvidia0 none bind,optional,create=file
lxc.mount.entry: /dev/nvidiactl dev/nvidiactl none bind,optional,create=file
lxc.mount.entry: /dev/nvidia-uvm dev/nvidia-uvm none bind,optional,create=file
lxc.mount.entry: /dev/nvidia-uvm-tools dev/nvidia-uvm-tools none bind,optional,create=file
lxc.mount.entry: /dev/nvidia-caps/nvidia-cap1 dev/nvidia-caps/nvidia-cap1 none bind,optional,create=file
lxc.mount.entry: /dev/nvidia-caps/nvidia-cap2 dev/nvidia-caps/nvidia-cap2 none bind,optional,create=file
lxc.idmap: u 0 100000 65535
lxc.idmap: g 0 0 1
lxc.idmap: g 1 100000 65535
